services:
  #java-backend:
    #build:
    #  context: ./demo
    #  dockerfile: Dockerfile
    #container_name: java-backend
    #ports:
    #  - "8081:8081"
    #environment:
    #  - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/testdb
    #depends_on:
    #  - mongo
    #  - microservico-embed

  microservico-embed:
    build:
      context: ./microservico-embed
    container_name: microservico-embed
    ports:
      - "8000:8000"
    volumes:
      - ./data:/mnt/data  # <--- Volume compartilhado
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/embed"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    extra_hosts:
      - "host.docker.internal:host-gateway"

    #depends_on:
    #  - mongo

#  frontend-angular:
#    container_name: frontend-angular
#    build:
#      context: ./frontend-angular/fortify-trainer-ui
#    ports:
#      - "4200:4200"
#    volumes:
#      - ./frontend-angular/fortify-trainer-ui:/app
#    working_dir: /app
#    command: ["npm", "run", "start", "--", "--host", "0.0.0.0"]
#    environment:
#      - CHOKIDAR_USEPOLLING=true

#  mongo:
#    image: mongo:6
#    container_name: mongo
#    ports:
#      - "27017:27017"
#    command: ["--bind_ip_all"]
#    volumes:
#      - mongo-data:/data/db

#volumes:
#  mongo-data:
